version: '3.8'

services:
  server1:
    build:
      context: ./server1
      dockerfile: Dockerfile
    container_name: server1
    ports:
      - "5002:5002"
    networks:
      - my_network
    depends_on:
      - server2

  server2:
    build:
      context: ./server2
      dockerfile: Dockerfile
    container_name: server2
    ports:
      - "5001:5001"
    networks:
      - my_network

  react_frontend:
    build:
      context: ./react_frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
